blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/frandi/trovec/discussions
    about: Ask questions or chat about Trovec here instead of opening an issue.
